### ISSUE TITLE
class version error?

### ISSUE THREAD

**Issue by qunge5211314** [hacker-works/mptt-jpa#1]
Error: (3, 33) Java: unable to access to the works.hacker.mptt.classic.MpttEntity
Wrong class file: /Users/mac/.m2/repository/works/hacker/mptt-jpa/0.1.1/mptt-jpa-0.1.1.jar!/works/hacker/mptt/classic/MpttEntity.class
The class file has the wrong version 55.0, which should be 52.0
Delete the file or make sure it is in the correct classpath subdirectory.

**Comment by qunge5211314** [comment]
By the way, my jdk version is 1.8.271

**Comment by hacker-works** [comment]
The whole project depends on Java 11.
Syntactically it won't compile on Java 8. I'm sorry.

**Comment by qunge5211314** [comment]
I see. Thank you

**Comment by hacker-works** [comment]
It would be helpful if you read this:

[Java 8 vs Java 11 – What are the Key Changes?](https://blog.idrsolutions.com/2019/05/java-8-vs-java-11-what-are-the-key-changes/)

The code base is using a lot the new `var`-keyword.

**Comment by qunge5211314** [comment]
Thank you very much

**Comment by gholizadeh** [comment]
I made a fork to use the library in java 8

**Comment by hacker-works** [comment]
@gholizadeh: just remove the maven-tag from the README in your fork, as the tag links it to the Java 11 version of the artefact. Also you should rewrite the USAGE-section as it loads the library as a POM-dependency.
